In [ ]:
# Numpy is fundamental library for scientific computing in python
# It handles the performing mathematical functions on arrays and matrices

In [1]:
import numpy as np
# install numpy using "!pip install numpy" in git bash
# numpy is basically a numerical python
# benefits of numpy array over list
# 1. array occupies less memory than list
# because of following reasons
# list does not store the integers directly.
# Each element is a pointer to a separate int object in memory.
# So memory includes:
# - The list container
# - A pointer for each element
# - A full Python int object for each number

# A NumPy array stores values in contiguous memory,
# using a fixed data type like int32 or float64.
# No pointers.
# No Python objects. Just raw bytes.

In [5]:
arr = np.array([1,2,3,4,5]) # creating one dimensional array
# we can we list or tuple inside np.array()
print(arr)
arr1 = np.array((1,2,3,4))
print(arr1)
print(type(arr))
print(type(arr1))

[1 2 3 4 5]
[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
print(arr.shape)

(5,)


In [ ]:
arr.reshape(1,5) # now the double square brackets shows it is 2 
# dimensional array

array([[1, 2, 3, 4, 5]])

In [10]:
# creating 2 dimensional array
arr2 = np.array([[1,2,3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]]
(1, 5)


In [11]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [18]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [12]:
import  sys

python_list = list(range(1000000))
numpy_array = np.arange(1000000)

In [13]:
print(sys.getsizeof(python_list[0])*len(python_list))
print(numpy_array.nbytes)

28000000
4000000


In [ ]:
# list supports non homogeneous elements

# 2. Measuring the performance -> the time taken for array is less when
#   compared to list

In [14]:
import time
ls1 = list(range(1000000))
ls2 = list(range(1000000))
start_time = time.time()
ls3=[x+y for x, y in zip(ls1,ls2)]
end_time = time.time()
print("time taken for list: ",end_time-start_time)

time taken for list:  0.05842852592468262


In [15]:
n1 = np.arange(1000000)
n2 = np.arange(1000000)
start_time = time.time()
n3 = n1 + n2
end_time = time.time()
print("time taken for array: ",end_time-start_time)

time taken for array:  0.003754854202270508


In [16]:
# 3. numpy array have more number of built in functions than list

l1 = list(range(5))
l2 = list(range(5))
print(l1+l2) # this concatenates but not adding
# to add we have to do as below
l3 = [x+y for x,y in zip(l1,l2)]
print(l3)

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
[0, 2, 4, 6, 8]


In [17]:
n1 = np.arange(5)
n2 = np.arange(5)
print(n1+n2)

[0 2 4 6 8]
