In [1]:
import numpy as np

In [2]:
# attributes of numpy array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("shape of array ",arr.shape)
print("dimensions of array",arr.ndim)
print("size (number of elements)",arr.size)
print("data type ",arr.dtype)
print("items size(in bytes) ",arr.itemsize) # ecah element size in array
print("bytes for entire array ",arr.nbytes)

'''
Memory usage  of an array
Total memory = itemsize * number_of_elements
'''

[[1 2 3]
 [4 5 6]]
shape of array  (2, 3)
dimensions of array 2
size (number of elements) 6
data type  int32
items size(in bytes)  4
bytes for entire array  24


'\nMemory usage  of an array\nTotal memory = itemsize * number_of_elements\n'

In [3]:
rev_q1 = np.array([10,12,9]) # revenue in Q1

In [4]:
print(rev_q1)
print(rev_q1.shape) # prints shape
print(rev_q1.ndim) # prints dimension
print(rev_q1.nbytes) # number of bytes occupied by array

[10 12  9]
(3,)
1
12


In [5]:
rev = np.array([[10,12,9],[23,15,19]]) # revneue in Q1 and Q2
print(rev)
print(rev.ndim)
print(rev[1,0]) # access first month revenue in Q2
rev[1,0] = 18 # manipulation of an element in array
print(rev)

[[10 12  9]
 [23 15 19]]
2
23
[[10 12  9]
 [18 15 19]]


In [6]:
print(rev.dtype) # prints data type of array

int32


In [7]:
# we can assign a data type to array
rev = np.array([[12,14,15],[18,19,23]],dtype= np.float64)
print(rev.dtype) # prints data type of array

float64


In [8]:
print(rev.nbytes) # prints the number of bytes occupied by array
print(rev.itemsize) # size of each item in array
print(rev.size) # prints size of array

48
8
6


In [9]:
print(rev.shape)
print(rev.reshape(3,2))
print(rev.shape)

(2, 3)
[[12. 14.]
 [15. 18.]
 [19. 23.]]
(2, 3)


In [ ]:
rev1 = np.array([[6,2,3],[1,5,2]])
print(np.sort(rev1)) # here axis is not specified so by default it takes axis = -1
# so it sorts row wise

print(np.sort(rev1, axis=1)) # sorts column wise


[[2 3 6]
 [1 2 5]]
[[2 3 6]
 [1 2 5]]


In [16]:
print(np.sort(rev,axis=None)) # array gets flattened if axis is None

[12. 14. 15. 18. 19. 23.]


In [12]:
# np.ones and np.zero is used in Deep learning for initializing weights
print(np.zeros((2,3))) # create 2*3 array with zeros
print(np.ones((2,4)))  # create 2*3 array with ones
print(np.eye(3)) # the diagonal of matrix is 1 and rest are 0 -> identity matrix


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
print(np.arange(20,30,2))# here 2 is step size

[20 22 24 26 28]


In [18]:
#Returns evenly spaced samples, calculated over the interval
print(np.linspace(1,2)) # by default  50 samples are printed

print(np.linspace(2,3,10))

[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ]
[2.         2.11111111 2.22222222 2.33333333 2.44444444 2.55555556
 2.66666667 2.77777778 2.88888889 3.        ]


In [22]:
# to make an array flat
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(np.ravel(arr1)) # creates view does not modify original array
print(arr1.ravel())
print(arr1)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [21]:
print(arr1.flatten())
print(arr1)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
# difference between ravel and flatten
# Use ravel() when you want speed and don’t need a guaranteed copy.
# Use flatten() when you want to ensure the result is independent of the
# original array

In [23]:
a = np.arange(6).reshape(2, 3)
b = a.ravel()
b[0] = 99 # a gets modified

In [24]:
print(a)

[[99  1  2]
 [ 3  4  5]]


In [ ]:
a = np.arange(6).reshape(2, 3)
b = a.flatten()
b[0] = 99 # a is not modified

In [26]:
print(a)

[[0 1 2]
 [3 4 5]]


In [27]:
a2 = np.arange(12)
a2 = a2.reshape(3,4)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
print(a2.min())
print(a2.max())
print(a2.sum(axis = 1)) # cal sum of each row
print(a2.sum(axis = 0)) # cal sum of each column
print(a2.std())
print(a2.mean())

0
11
[ 6 22 38]
[12 15 18 21]
3.452052529534663
5.5


In [30]:
# numpy vectorised operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# element wise addition
print("addition : ",arr1+arr2)

# element wise subtraction
print("subtraction: ",arr1-arr2)

# element with multiplication
print("multiplication: ",arr1 * arr2)

# element wise division

print("division: ",arr1/arr2)

addition :  [11 22 33 44 55]
subtraction:  [ -9 -18 -27 -36 -45]
multiplication:  [ 10  40  90 160 250]
division:  [0.1 0.1 0.1 0.1 0.1]


In [ ]:
# universal functions -> functions that apply to the entire array

arr = np.array([2,4,6,8,9])
# square root
np.sqrt(arr)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.        ])

In [32]:
# exponential
np.exp(arr)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       8.10308393e+03])

In [33]:
np.sin(arr)

array([ 0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,  0.41211849])

In [34]:
# natual log
np.log(arr)

array([0.69314718, 1.38629436, 1.79175947, 2.07944154, 2.19722458])