In [1]:
import numpy as np
# q1 and q2 are sales of different products in different countries
                # country
q1 = np.array([[200,220,250],  # product A
               [150,180,210],  # product B
               [300,330,360]]) # product C
q2 = np.array([[209,231,259],
               [155,192,222],
               [310,340,375]])

In [2]:
print(q1 + q2) # gives total revenue of each product in different countries

[[409 451 509]
 [305 372 432]
 [610 670 735]]


In [3]:
print(q2-q1)  # sales qrowth in q1


[[ 9 11  9]
 [ 5 12 12]
 [10 10 15]]


In [4]:
print(((q2-q1)* 100)/q1) # sales growth % from Q1

[[4.5        5.         3.6       ]
 [3.33333333 6.66666667 5.71428571]
 [3.33333333 3.03030303 4.16666667]]


In [5]:
prices = np.array([[10,12,11], # prices of product A in different regions
                   [8,9,10],   # prices of product B in different regions
                   [15,16,17]])

In [6]:
q1_revenue = q1 * prices
print(q1_revenue)

[[2000 2640 2750]
 [1200 1620 2100]
 [4500 5280 6120]]


In [7]:
# there is 20 % discount on products in q1, cal discount value
discount_rev = q1_revenue * 0.2
print(discount_rev)

[[ 400.  528.  550.]
 [ 240.  324.  420.]
 [ 900. 1056. 1224.]]


In [8]:
net_revenue = q1_revenue - discount_rev
print(net_revenue)

[[1600. 2112. 2200.]
 [ 960. 1296. 1680.]
 [3600. 4224. 4896.]]


In [9]:
# total discount on all products in all regions

print(np.sum(discount_rev))

5642.0


In [10]:
# dot product

features = np.array([
    [2000,3], # house 1
    [1800,2]  # house 2
])

In [11]:
weights = np.array([150,50000])

print(np.dot(features,weights))

[450000 370000]


In [ ]:
# cross product

c = np.array([1,2,3])
d = np.array([4,5,6])
print(np.cross(c,d))