In [1]:
import numpy as np

a1 = np.array([1,2,3,4,5,6,7,8])

In [2]:
print(a1[0:2]) # print from 0 to 1 , index 2 is not included

[1 2]


In [3]:
print(a1[2:])  # print from index 2 till end

[3 4 5 6 7 8]


In [4]:
print(a1[-1])

8


In [5]:
print(a1[-1:0]) # prints empty as moving from -1 to 0 is in -ve direction
# where as increment of 1 is in +ve direction, so both are contradicting

[]


In [6]:
print(a1[-1:0:-1])

[8 7 6 5 4 3 2]


In [7]:
print(a1[-3:])

[6 7 8]


In [8]:
b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [9]:
# print 6 from b array

print(b[1,2])

6


In [10]:
# print 7 from array b

print(b[2,0])

7


In [11]:
print(b[-1])

[7 8 9]


In [12]:
print(b[-1,0:2])

[7 8]


In [13]:
print(b[:,1:3])

[[2 3]
 [5 6]
 [8 9]]


In [14]:
print(b[1:,1:])

[[5 6]
 [8 9]]


In [15]:
# modify array elements

b[0,0] = 2
print(b)

[[2 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
b[1:,1:]=[[50,60],[70,80]]
print(b)

[[ 2  2  3]
 [ 4 50 60]
 [ 7 70 80]]


In [18]:
b[1:,1:] = 100
print(b)

[[  2   2   3]
 [  4 100 100]
 [  7 100 100]]


In [ ]:
# hstack , vstack

In [19]:
# Customer ID, Name
c = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])

In [20]:
# Customer Id, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

In [21]:
print(np.hstack((c,d))) # merges horizontally

[['101' 'Mira' '101' '250.5' '2023-08-01']
 ['102' 'Abdul' '102' '150.0' '2023-08-02']
 ['103' 'Andrea' '103' '300.75' '2023-08-01']]


In [22]:
e = np.array([
    [104, 'Venkat'],
    [105, 'John'],
    [106, 'Kathy'],
])


In [23]:
print(e)

[['104' 'Venkat']
 ['105' 'John']
 ['106' 'Kathy']]


In [24]:
print(np.vstack((c,e)))

[['101' 'Mira']
 ['102' 'Abdul']
 ['103' 'Andrea']
 ['104' 'Venkat']
 ['105' 'John']
 ['106' 'Kathy']]


In [25]:
# splitting the data using hsplit,vsplit

transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

In [26]:
print(np.hsplit(transactions,[3]))

[array([['101', 'Mohan', '250.5'],
       ['102', 'Bob', '150.0'],
       ['103', 'Fatima', '300.75'],
       ['104', 'David', '400.2'],
       ['105', 'Aryan', '330.1']], dtype='<U32'), array([['2023-08-01'],
       ['2023-08-02'],
       ['2023-08-01'],
       ['2023-08-03'],
       ['2023-08-04']], dtype='<U32')]


In [27]:
a,b = np.hsplit(transactions,[3])

In [28]:

print(a)
print(b)

[['101' 'Mohan' '250.5']
 ['102' 'Bob' '150.0']
 ['103' 'Fatima' '300.75']
 ['104' 'David' '400.2']
 ['105' 'Aryan' '330.1']]
[['2023-08-01']
 ['2023-08-02']
 ['2023-08-01']
 ['2023-08-03']
 ['2023-08-04']]


In [29]:
c,d = np.vsplit(transactions,[3])
print(c)
print(d)

[['101' 'Mohan' '250.5' '2023-08-01']
 ['102' 'Bob' '150.0' '2023-08-02']
 ['103' 'Fatima' '300.75' '2023-08-01']]
[['104' 'David' '400.2' '2023-08-03']
 ['105' 'Aryan' '330.1' '2023-08-04']]
