In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [3]:
# get the values which are greater than 5
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [6]:
# get the data greater than 5 and less than 8

arr[(arr>5) & (arr<8)]

array([6, 7])

In [8]:
monthly_sales = np.array([30,33,35,28,42])
sales_target = 32
result = monthly_sales > sales_target
print(result) 

[False  True  True False  True]


In [9]:
# get the monthly sales which are greater than sales target
monthly_sales[monthly_sales>sales_target]

array([33, 35, 42])

In [ ]:
# find max sales
np.max(monthly_sales)

42

In [ ]:
# argmax in NumPy tells you the index of the maximum value in an array.
index = np.argmax(monthly_sales)
print(index)

# what are sales when they peak
monthly_sales[index]

4


42

In [23]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

In [30]:
# in transactions get the max transaction amount
amounts = transactions[:,2]
amounts = amounts.astype(float)
print(amounts)
print(max(amounts))

[250.5  150.   300.75 400.2  330.1 ]
400.2


In [25]:
 # gets the index of max transaction amount
index = np.argmax(amounts)
print(index)
print(amounts[index])

3
400.2


In [26]:
# # prints record of max transaction amount

transactions[index]

array(['104', 'David', '400.2', '2023-08-03'], dtype='<U32')

In [28]:
# get arecord with transaction id 102

transactions[transactions[:,0] == '102']

array([['102', 'Bob', '150.0', '2023-08-02']], dtype='<U32')